const varkData = [
  {
    ques_name:
      "I need to find the way to a shop that a friend has recommended. I would:",
    option1: "find out where the shop is in relation to somewhere I know.",
    option1_type: "K",
    option2: "ask my friend to tell me the directions.",
    option2_type: "A",
    option3: "write down the street directions I need to remember.",
    option3_type: "R",
    option4: "use a map.",
    option4_type: "V",
  },
  {
    ques_name:
      "A website has a video showing how to make a special graph or chart. There is a person speaking,some list and words describing what to do and some diagrams. I will learn most from:",
    option1: "seeing the diagrams.",
    option1_type: "V",
    option2: "listening.",
    option2_type: "A",
    option3: "reading the words.",
    option3_type: "R",
    option4: "watching the actions.",
    option4_type: "K",
  },
  {
    ques_name:
      "I want to find out more about a tour that I am going on. I would:",
    option1: "look at details about the highlights and activities on the tour.",
    option1_type: "K",
    option2: "use a map and see where the places are.",
    option2_type: "V",
    option3: "read about the tour on the itinerary.",
    option3_type: "R",
    option4:
      "talk with the person who planned the tour or others who are going on the tour.",
    option4_type: "A",
  },
  {
    ques_name:
      "When choosing a career or area of study, these are important for me:",
    option1: "Applying my knowledge in real situations. ",
    option1_type: "K",
    option2: "Communicating with others through discussion. ",
    option2_type: "A",
    option3: "Working with designs, maps or charts. ",
    option3_type: "V",
    option4: " Using words well in written communications.",
    option4_type: "R",
  },
  {
    ques_name: "When I am learning I:",
    option1: "like to talk things through.",
    option1_type: "A",
    option2: "see patterns in things",
    option2_type: "V",
    option3: "use examples and applications",
    option3_type: "K",
    option4: "read books, articles and handouts.",
    option4_type: "R",
  },
  {
    ques_name:
      "I want to save more money and to decide between a range of options. I would:",
    option1:
      "consider examples of each option using my financial information. ",
    option1_type: "K",
    option2: "read a print brochure that describes the options in detail. ",
    option2_type: "R",
    option3:
      "use graphs showing different options for different time periods. ",
    option3_type: "V",
    option4: "talk with an expert about the options. ",
    option4_type: "A",
  },
  {
    ques_name:
      "I want to learn how to play a new board game or card game. I would:",
    option1: "watch others play the game before joining in. ",
    option1_type: "K",
    option2: "listen to somebody explaining it and ask questions. ",
    option2_type: "A",
    option3:
      "use the diagrams that explain the various stages, moves and strategies in the game",
    option3_type: "V",
    option4: "read the instructions.",
    option4_type: "R",
  },
  {
    ques_name:
      "I have a problem with my heart. I would prefer that the doctor:",
    option1: "gave me something to read to explain what was wrong.",
    option1_type: "R",
    option2: "used a plastic model to show me what was wrong.",
    option2_type: "K",
    option3: "described what was wrong.",
    option3_type: "A",
    option4: "showed me a diagram of what was wrong. ",
    option4_type: "V",
  },
  {
    ques_name: "I want to learn to do something new on a computer. I would:",
    option1: "read the written instructions that came with the program. ",
    option1_type: "R",
    option2: "talk with people who know about the program.",
    option2_type: "A",
    option3: "start using it and learn by trial and error. ",
    option3_type: "K",
    option4: "follow the diagrams in a book.",
    option4_type: "V",
  },
  {
    ques_name: "When learning from the Internet I like:",
    option1: "videos showing how to do or make things. ",
    option1_type: "K",
    option2: "interesting design and visual features.",
    option2_type: "V",
    option3: "interesting written descriptions, lists and explanations",
    option3_type: "R",
    option4: "audio channels where I can listen to podcasts or interviews.",
    option4_type: "A",
  },
  {
    ques_name: "I want to learn about a new project. I would ask for:",
    option1:
      "diagrams to show the project stages with charts of benefits and costs.",
    option1_type: "V",
    option2: "a written report describing the main features of the project. ",
    option2_type: "R",
    option3: "an opportunity to discuss the project.",
    option3_type: "A",
    option4: " examples where the project has been used successfully.",
    option4_type: "K",
  },
  {
    ques_name: "I want to learn how to take better photos. I would:",
    option1: "ask questions and talk about the camera and its features. ",
    option1_type: "A",
    option2: "use the written instructions about what to do. ",
    option2_type: "R",
    option3: "use diagrams showing the camera and what each part does. ",
    option3_type: "V",
    option4:
      "use examples of good and poor photos showing how to improve them. ",
    option4_type: "K",
  },
  {
    ques_name: "I prefer a presenter or a teacher who uses:",
    option1: "demonstrations, models or practical sessions",
    option1_type: "K",
    option2: " question and answer, talk, group discussion, or guest speakers.",
    option2_type: "A",
    option3: "handouts, books, or readings. ",
    option3_type: "R",
    option4: "diagrams, charts, maps or graphs. ",
    option4_type: "V",
  },
  {
    ques_name:
      "I have finished a competition or test and I would like some feedback. I would like to have feedback:",
    option1: "using examples from what I have done. ",
    option1_type: "K",
    option2: "using a written description of my results. ",
    option2_type: "R",
    option3: "from somebody who talks it through with me. ",
    option3_type: "A",
    option4: "using graphs showing what I achieved. ",
    option4_type: "V",
  },
  {
    ques_name:
      "I want to find out about a house or an apartment. Before visiting it I would want:",
    option1: "to view a video of the property.",
    option1_type: "K",
    option2: "a discussion with the owner.",
    option2_type: "A",
    option3: "a printed description of the rooms and features.",
    option3_type: "R",
    option4: "a plan showing the rooms and a map of the area. ",
    option4_type: "V",
  },
  {
    ques_name:
      "I want to assemble a wooden table that came in parts (kitset). I would learn best from:",
    option1: "diagrams showing each stage of the assembly. ",
    option1_type: "V",
    option2: "advice from someone who has done it before. ",
    option2_type: "A",
    option3: "written instructions that came with the parts for the table.",
    option3_type: "R",
    option4: "watching a video of a person assembling a similar table. ",
    option4_type: "K",
  }
];

export default varkData